config/routes.rb
Rails.application.routes.draw do

  post ':id/follow_user', to: 'friendships#follow_user', as: :follow_user
  post ':id/unfollow_user', to: 'friendships#unfollow_user', as: :unfollow_user
 

  get 'users/search', to: 'users#search', as: 'search_page'
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users, only: [:show]
  root to: 'phrases#index'

  resources :phrases do 
  	resources :comments
  	member do 
  		get 'like'
  		get 'unlike'
  	end
  end

  get '/ownphrases', to: 'users#index'
  get '/tagged', to: "phrases#tagged", as: :tagged

  
  get 'friendships/following', to: 'friendships#following'
  get 'friendships/followers', to: 'friendships#follower'


end

app/controllers/phrases_controller.rb
class PhrasesController < ApplicationController
	before_action :set_phrase, only: [:edit, :show, :update, :destroy,
	 :like, :unlike]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@phrases = Phrase.recent.all.page params[:page]
		@users = User.all
		unless current_user.blank?
			@ownphrases = Phrase.recent.where(:user_id => current_user.id).page params[:page]
			@followedphrases = Phrase.of_followed_users(current_user.following).
				recent.page params[:page]

			@feedphrases = (@followedphrases + @ownphrases).sort_by(&:created_at).
				reverse

		end
		
		# Find phrase's topics
		@topics = ActsAsTaggableOn::Tagging.includes(:tag).where(context: 'topics').
			map { |tagging| { 'name' => tagging.tag.name } }.pluck("name").uniq
		@most_used_topics = ActsAsTaggableOn::Tag.most_used(5).map(&:name)
	end

	def show

	end

	def new
		@phrase = current_user.phrases.build

	end

	def edit

	end

	def create
		@phrase = current_user.phrases.build(phrase_params)
		logger.debug "@phrase is: #{@phrase.inspect}"
		if @phrase.save
			flash[:notice] = "Faphra was successfully created"
			redirect_to root_path
		else
			render :new
		end
	end

	def update
		if @phrase.update(phrase_params)
			flash[:notice] = "Faphra was updated successfully!"
			redirect_to phrase_path(@phrase)
		else
			render 'edit'
		end 
	end

	def destroy
		@phrase.destroy
		flash[:notice] = "Faphra was deleted successfully"

		redirect_to phrases_path
	end

	def like 
		if @phrase.liked_by current_user 
			respond_to do |format|
				format.html { redirect_to :back }
				format.js
			end
		end
	end

	def unlike
		if @phrase.unliked_by current_user
			respond_to do |format|
				format.html { redirect_to :back }
				format.js
			end
		end
	end

	def tagged
		
	  if params[:topic].present?
	    @phrases = Phrase.tagged_with(params[:topic])
	  else
	    @phrases = Phrase.all
	  end
	end




	private

	  def set_phrase 
	  	@phrase = Phrase.find(params[:id])
	  end

	  def phrase_params
	  	params.require(:phrase).permit(:id, :body, :topic_list)
	  end

end

app/helpers/phrases_helper.rb
module PhrasesHelper 

	def display_likes(phrase)
		votes = phrase.votes_for.up.by_type(User)
		return list_likers(votes) if votes.size <= 8
		count_likers(votes)
	end

	def liked_phrase(phrase)
		unless current_user.blank?
			if current_user.voted_for? phrase
				return link_to '', unlike_phrase_path(phrase), remote: true,
				id: "like_#{phrase.id}", 
				class: 'btn btn-light text-dark btt-like btn fa fa-heart' 
			else 
				return link_to '', like_phrase_path(phrase), remote: true,
				id: "like_#{phrase.id}", 
				class: 'btn btn-outline-light text-dark btt-like btn fa fa-heart-o'
			end				 
		end

	end

	private

		def list_likers(votes)
			user_names = []

			unless votes.blank?
				votes.voters.each do |voter|
					user_names.push(voter.username.capitalize)
				end

			user_names.to_sentence.html_safe + like_plural(votes)
			end
		end

		def count_likers(votes)
			vote_count = votes.size 
			vote_count.to_s + ' likes'

		end

		def like_plural(votes)
			return ' like this' if votes.count > 1
			' likes this'
		end

end

app/views/phrases/_categories.html.erb
<div class="card rounded border-light shadow p-3 mb-5">	
	<h4 class="card-header text-center">Faphra's Topics</h4>
	<p></p>

	<p></p>
	<ul class="list-group list-group-flush">
		
			<div class="topic">
			  <% @most_used_topics.each do |t| %>
			  <li class="list-group-item mb-2 pb-0">
			  	<h5 class="text-center">
			    <%= link_to t.upcase, tagged_path(topic: t), class: "text-decoration-none" %>
				</h5>
			  </li>
			  <% end %>
			</div>

	</ul>
 
</div>

app/views/phrases/_feed.html.erb
<ul>
	<% @phrases.each do |phrase| %>
       <div class="card rounded border-light shadow p-3 mb-4 ">

	  	  <div class="card-block d-flex">
		  	<p class="image ">
		  		<%= gravatar_image_tag(phrase.user.email, 
				  :gravatar => { :size => 40 }, alt: phrase.user.name) %>
		  	</p>

	        <div class="col">
	  		  <h5 class="card-title"><%= phrase.user.name %></h5>
	  		  <h6 class="card-subtitle mb-2 text-muted">
	  		  	<%= phrase.user.username %>
	  		  </h6>
	  	    </div>
	  	  </div>

		  <div class="row">
		  	<div class="col">
			  <p class="card-text">
				<em><%= phrase.body %></em>
			  </p>
			  <span class="row border-bottom"></span>

			  </div>
			</div>

			<div id="comments_<%= phrase.id %>">
			  <% if phrase.comments %>
			  	<%= render phrase.comments, phrase: phrase %>
			  <% end %>
			</div>
			    
		</div> 
	<% end %>
</ul>	

app/views/phrases/_form.html.erb
<%= form_for(Phrase.new, :url => { :controller => "phrases", :action => "create" }) do |f| %>


    <h5 class="card-title">Today's Favorite Phrase</h5>
    <div class="col-md-12">
   		 <%= f.text_area :body, class: "form-control",
   		 placeholder: "Add your new favorite phrase...", autofocus: true %><br />
    </div>
    <div>
    	<%= f.label :topic_list, "Topic" %>
		<%= 
		  f.text_field :topic_list, 
		  placeholder: 'Topic of faphra...'
		%>
    </div>

    <%= f.submit "Create faphra", class: "btn ml-1 btn-primary btn-lg btn-xlarge" %>

<% end %>

app/views/phrases/_likes.html.erb
<div id="likes_<%= phrase.id %>"> 
  <%= display_likes phrase %>
</div>

app/views/phrases/_profile.html.erb
<div class="card rounded border-light shadow p-3 ">
	<h5 class="card-header text-center mb-2">Profile</h5>

    <div class="card-block d-flex">
	  	<p class="image">
	  		<%= gravatar_image_tag(current_user.email, 
					  size: 64, alt: current_user.name) %>
	  	</p>
      <div class="col">
        <p></p>
        <h5 class="card-title"><%= current_user.name %></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%= current_user.username %></h6>
      </div>
    </div>
    
  <span class="border-bottom"></span>
  <div class="row">
    <div class="col text-secondary">
      <h6>Faphras</h6>
      <p><%= link_to @ownphrases.count, ownphrases_path, class: "text-info" %></p>
    </div>
    <div class="col text-secondary">
      <h6>Following</h6>
      <p class="text-info"><%= link_to current_user.following.count, 
        friendships_following_path, class: "text-info" %></p>
    </div>
    <div class="col text-secondary">
      <h6>Followers</h6>
      <p class="text-info"><%= link_to current_user.followers.count, 
        friendships_followers_path, class: "text-info" %></p>
    </div>
  </div>
</div>

app/views/phrases/_trends.html.erb
<div class="card rounded border-light shadow p-3 mb-5">	
	<h5 class="card-header text-center">Trends</h5>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Trend 1</li>
    <li class="list-group-item">Trend 2</li>
    <li class="list-group-item">Trend 3</li>
    <li class="list-group-item">Trend 4</li>
  </ul>
</div>

app/views/phrases/_user_feed.html.erb
<ul>
	<div class="card rounded border-light flex-row flex-wrap shadow p-3 mb-4 ">
		<% if user_signed_in? %>
	  	<div class="card-block d-flex">
		  	<p class="image ">
		  		<%= gravatar_image_tag(current_user.email, 
					   size: 64, alt: current_user.name) %>
		  	</p>
	    </div>
	    <div class="col">
	    	<%= render 'form', phrase: @phrase %>
	    </div>
	    <% end %>
	</div>
	    <p></p>

	<% @feedphrases.each do |phrase| %>
       <div class="card rounded border-light shadow p-3 mb-4 ">

	  	  <div class="card-block d-flex">
		  	<p class="image ">
		  		<%= gravatar_image_tag(phrase.user.email, 
				  :gravatar => { :size => 40 }, alt: phrase.user.name) %>
		  	</p>

	        <div class="col">
	  		  <h5 class="card-title"><%= phrase.user.name %></h5>
	  		  <h6 class="card-subtitle mb-2 text-muted">
	  		  	<%= phrase.user.username %>
	  		  </h6>
	  	    </div>
	  	  </div>

		  <div class="row">
		  	<div class="col">
			  <p class="card-text">
				<em><%= phrase.body %></em>
			  </p>
			  <span class="row border-bottom"></span>

				<div class="row">
					<% if current_user.present? %>
						<div class="col-1">
						  <%= liked_phrase phrase %>
						</div>
						<div class="col-4 ml-3">
							<%= render 'phrases/likes', phrase: phrase %>
						</div>
						<div class="col-auto">
						</div>
					<% end %>

					<div class="col-2"></div>

					<div class="col-auto justify-content-end">
					<% unless current_user.blank? %>
						<% if phrase.user.id == current_user.id %>
						  <div class="col-auto">
							<%= link_to "", phrase_path(phrase), 
							class: "fa fa-eye mr-2 ph-icon" %>
							<%= link_to "", edit_phrase_path(phrase), 
							class: "fa fa-pencil-square-o mr-2 ph-icon" %>
							<%= link_to "", phrase_path(phrase), method: :delete, 
								data: { confirm: "Are you sure?" }, 
								class: "fa fa-trash ph-icon" %>
						  </div>
						<% end %>
					<% end %>
				</div>

				</div>
				<span class="row border-bottom"></span>
			  </div>
			</div>

			<div id="comments_<%= phrase.id %>">
			  <% if phrase.comments %>
			  	<%= render phrase.comments, phrase: phrase %>
			  <% end %>
			</div>

			<dir class="row">
				<% if user_signed_in? %>
				   <div class="form">
					<div class="card-block d-flex">	
					  <div class="col">	
					  	<%= form_for( [phrase, phrase.comments.new], remote: true) do |f| %>
							<%= f.text_field :content, class: "form-control form-control-lg",
							id: "comment_content_#{phrase.id}",
			   					placeholder: "Add a comment...", autofocus: true %>
			   		  </div>
			   		  <div class="col-1">
							<%= f.submit "Submit", class: "btn btn-outline-primary mr-2" %>
						<% end %>
					  </div>
					</div>
			      </div>
				<% end %>
			</dir>
			    
		</div> 
	<% end %>
</ul>	

app/views/phrases/edit.html.erb
<%= render 'shared/page_title', title: "editing faphra" %>

<%= render 'form', phrase: @phrase %>

<p class="d-flex justify-content-end">
	<%= link_to "Cancel", phrases_path, class: "btn btn-primary mr-2" %>
</p>

app/views/phrases/index.html.erb
<%= render 'shared/page_title', title: "Faphra App" %>
<h4 class="text-center text-secondary">A place to share your Favorite Phrases</h4>

<div class="container-fluid">
<div>
	<p class="mt-5"></p>
</div>

<% if user_signed_in? %>
	<div class="row">
	  <div class="col-sm-3">	
		<%= render 'profile' %>
	  </div>

	  <div class="col-sm-6">	
		<%= render 'user_feed' %>
	  </div>

	  <div class="col-sm-3">	
		<%= render 'categories' %>
	  </div>
	</div>

	<nav aria-label="Page navigation example">
	<div class="container pagination justify-content-center" >
  		<%= paginate @phrases %>
	</div>
	</nav>

<% else %>
	<div class="row">
	  <div class="col-sm-8">	
		<%= render 'feed' %>
	  </div>

	  <div class="col-sm-4">	
		<%= render 'categories' %>
	  </div>
	</div>

	<nav aria-label="Page navigation example">
	<div class="container pagination justify-content-center" >
  		<%= paginate @phrases %>
	</div>
	</nav>

<% end %>
</div>

app/views/phrases/like.js.erb
$("#like_<%= @phrase.id %>").removeClass("fa-heart-o").addClass("fa-heart");
$("#likes_<%= @phrase.id %>").html("<%= j (render partial: 'phrases/likes', locals: { phrase: @phrase} ) %>");

app/views/phrases/new.html.erb
<%= render 'shared/page_title', title: "create a new faphra" %>
<p>My new faphra</p>

<%= render 'form', phrase: @phrase %>

app/views/phrases/show.html.erb
<%= render 'shared/page_title', title: "Showing faphra" %>
<p>
  <strong>Phrase:</strong>
  <%= @phrase.body %>
</p>

<p class="d-flex justify-content-end">
	<%= link_to 'Edit', edit_phrase_path(@phrase), class: "btn btn-primary btn-lg mr-2" %>
	<%= link_to 'Back', phrases_path, class: "btn btn-primary btn-lg mr-2" %>
</p>

app/views/phrases/tagged.html.erb
<div class="container">

<h2 class="text-center">Faphras about: <%= params[:topic].capitalize %></h2>
<hr />

  <ul>
	<% @phrases.recent.each do |phrase| %>
       <div class="card rounded border-light shadow p-3 mb-4 ">
 		<div class="row">	
	  	  <div class="card-block d-flex">
		  	<p class="image ">
		  		<%= gravatar_image_tag(phrase.user.email, 
				  :gravatar => { :size => 40 }, alt: phrase.user.name) %>
		  	</p>
		 
	        <div class="col">
	  		  <h5 class="card-title"><%= phrase.user.name %></h5>
	  		  <h6 class="card-subtitle mb-2 text-muted">
	  		  	<%= phrase.user.username %>
	  		  </h6>
	  	    </div>
	  	  </div>
	  	  <div class="col">
	  	  	<% unless current_user.id == phrase.user.id %>
		  	  <% if current_user_is_following(current_user.id, phrase.user.id) %>
	              <%= link_to 'Following', unfollow_user_path(phrase.user), remote: true,
	                class: 'btn unfollow-button btn-outline-primary ml-2 w-auto', id: 'follow-button', 
	                method: :post %>
	            <% else %>
	              <%= link_to 'Follow', follow_user_path(phrase.user), remote: true,
	                class: 'btn follow-button btn-outline-primary ml-2', id: 'unfollow-button', 
	                method: :post %>
	          <% end %>
	         <% end %> 
      		</div>

      		</div>

		  <div class="row">
		  	<div class="col">
			  <p class="card-text">
				<em><%= phrase.body %></em>
			  </p>
			  <span class="row border-bottom"></span>

			  </div>
			</div>

			<div id="comments_<%= phrase.id %>">
			  <% if phrase.comments %>
			  	<%= render phrase.comments, phrase: phrase %>
			  <% end %>
			</div>
			    
		</div> 
	<% end %>
  </ul>	
</div>

app/views/phrases/unlike.js.erb
$("#like_<%= @phrase.id %>").removeClass("fa-heart").addClass("fa-heart-o");
$("#like_<%= @phrase.id %>").removeAttr('href').attr('href', '/phrases/<%= @phrase.id %>/like');
$("#likes_<%= @phrase.id %>").html("<%= j (render partial: 'phrases/likes', locals: { phrase: @phrase} ) %>");