config/routes.rb
Rails.application.routes.draw do

  post ':id/follow_user', to: 'friendships#follow_user', as: :follow_user
  post ':id/unfollow_user', to: 'friendships#unfollow_user', as: :unfollow_user
 

  get 'users/search', to: 'users#search', as: 'search_page'
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users, only: [:show]
  root to: 'phrases#index'

  resources :phrases do 
  	resources :comments
  	member do 
  		get 'like'
  		get 'unlike'
  	end
  end

  get '/ownphrases', to: 'users#index'
  get '/tagged', to: "phrases#tagged", as: :tagged

  
  get 'friendships/following', to: 'friendships#following'
  get 'friendships/followers', to: 'friendships#follower'


end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_user, only: [:follow_user, :unfollow_user]
	
  def follow_user
    if current_user.follow @user.id
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js 
      end
    end
  end
  
  def unfollow_user
    if current_user.unfollow @user.id
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js 
      end
    end
  end

def follower
  id = current_user.followers.pluck(:id)
  @follower = User.find_by(id: id)
end

def following
  id = current_user.following.pluck(:id)
  @following = User.find_by(id: id)
end
  

  private

    def set_user
          @user = User.find_by! id: params[:id]
    end

end

app/helpers/friendships_helper.rb
module FriendshipsHelper

  def current_user_is_following(current_user_id, followed_user_id)
    relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
    return true if relationship
  end

end

app/views/friendships/_who_to_follow.html.erb
<div class="card rounded border-light shadow p-3 mb-5">	
	<h5 class="card-header text-center">Who to Follow</h5>
	<p></p>
  
  	<% @users.each do |user| %>
  	  <% if user != current_user %>
	    
	      <ul class="list-group list-group-flush">
	      	<li class="card-block d-flex list-group-item mb-2 pb-0">
	    	<p class="image mr-2">
	    	<%= gravatar_image_tag(user.email, :gravatar => { :size => 40 },
								   alt: user.name) %>
			</p>
			<p>
			<strong><%= user.name %></strong><br />
			<small><%= user.username %></small><br />

            <% if current_user_is_following(current_user.id, user.id) %>
              <%= link_to 'Following', unfollow_user_path(user), remote: true,
                class: 'btn unfollow-button', id: 'unfollow-button', 
                method: :post %>
            <% else %>
              <%= link_to 'Follow', follow_user_path(user), remote: true,
                class: 'btn follow-button', id: 'unfollow-button', 
                method: :post %>
            <% end %>
			
		</li>

		</ul>
	  <% end %>
    <% end %>
 
</div>

app/views/friendships/follow_user.html.erb
<h1>Friendships#follow_user</h1>
<p>Find me in app/views/friendships/follow_user.html.erb</p>

app/views/friendships/follow_user.js.erb
$('#follow-button').attr('class', 'btn unfollow-button btn-outline-primary')
                   .text('Following')
                   .attr('href', "/<%= @user.id %>/unfollow_user")
                   .attr('id', 'unfollow-button');
   

app/views/friendships/follower.html.erb
<%= render 'shared/page_title', title: "user's followers" %>

<div class="container">
  <ul>

	<% current_user.followers.each do |user| %>
	    <div class="card-block w-50 d-flex mx-auto justify-content-between">
			<div class="row">

		  	<p class="image">
		  		<%= gravatar_image_tag(user.email, 
						  size: 64, alt: user.name) %>
		  	</p>
	      <div class="col">
	        <p></p>
	        <h5 class="card-title"><%= user.name %></h5>
	        <h6 class="card-subtitle mb-2 text-muted"><%= link_to user.username, user_path(user) %></h6>
	      </div>
	    </div>
	    <div class="col-2">
            <% if current_user_is_following(current_user.id, user.id) %>
              <%= link_to 'Following', unfollow_user_path(user), remote: true,
                class: 'btn unfollow-button btn-outline-primary', id: 'follow-button', 
                method: :post %>
            <% else %>
              <%= link_to 'Follow', follow_user_path(user), remote: true,
                class: 'btn follow-button btn-outline-primary', id: 'unfollow-button', 
                method: :post %>
            <% end %>
	    </div>
	   	</div>
    <% end %>

  </ul>
</div>

app/views/friendships/following.html.erb
<%= render 'shared/page_title', title: "users following" %>

<div class="container">
  <ul>

	<% current_user.following.each do |user| %>
	    <div class="card-block w-50 d-flex mx-auto justify-content-between">
			<div class="row">

		  	<p class="image">
		  		<%= gravatar_image_tag(user.email, 
						  size: 64, alt: user.name) %>
		  	</p>
	      <div class="col">
	        <p></p>
	        <h5 class="card-title"><%= user.name %></h5>
	        <h6 class="card-subtitle mb-2 text-muted"><%= link_to user.username, user_path(user) %></h6>
	      </div>
	    </div>
	    <div class="col-2">
	    <%= link_to 'Following', unfollow_user_path(user), remote: true,
	        class: 'btn unfollow-button btn-outline-primary', id: 'follow-button', 
	        method: :post %>
	    </div>
	   	</div>
    <% end %>

  </ul>
</div>

app/views/friendships/unfollow_user.html.erb
<h1>Friendships#unfollow_user</h1>
<p>Find me in app/views/friendships/unfollow_user.html.erb</p>

app/views/friendships/unfollow_user.js.erb
$('#unfollow-button').text('Follow')
                     .attr('class', 'btn follow-button btn-outline-primary')
                     .attr('href', "/<%= @user.id %>/follow_user")
                     .attr('id', 'follow-button');
                     