config/routes.rb
Rails.application.routes.draw do

  post ':id/follow_user', to: 'friendships#follow_user', as: :follow_user
  post ':id/unfollow_user', to: 'friendships#unfollow_user', as: :unfollow_user
 

  get 'users/search', to: 'users#search', as: 'search_page'
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users, only: [:show]
  root to: 'phrases#index'

  resources :phrases do 
  	resources :comments
  	member do 
  		get 'like'
  		get 'unlike'
  	end
  end

  get '/ownphrases', to: 'users#index'
  get '/tagged', to: "phrases#tagged", as: :tagged

  
  get 'friendships/following', to: 'friendships#following'
  get 'friendships/followers', to: 'friendships#follower'


end

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col">
    <% flash.each do |name, msg| %>
      <% if name == 'notice' %>
      	<% name = 'primary' %>
      <% else %>
      	<% name = 'danger' %>
      <% end %>

      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">×</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container-fluid">
    <%= link_to "FAPHRA", root_path, class: "navbar-brand" %>
    
      <% if user_signed_in? %>

        <%= form_tag(search_page_path, :method => "get", 
           class: 'navbar-form navbar-left') do %>  
          <div class="input-group">  
            <%= search_field_tag :search, params[:search], 
                placeholder: "Search a user", class: "form-control" %>  
            <div class="input-group-btn">  
              <%= submit_tag "Search", 
                :class => 'btn btn-light btn-lg ml-3 fa fa-search',:name => nil%>  
            </div>  
          </div>  
        <% end %>



        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
          <%= link_to current_user.name, edit_user_registration_path, 
          class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, 
            class: "nav-link" %>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <%= link_to "Log In", user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, 
              class: "nav-link" %>
            </li>
      <% end %>
       </ul>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Faphra</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/messages' %>

    <%= render 'layouts/navbar' %>
    
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>